CREATE USER C##DBELOPER IDENTIFIED BY DBELOPER;
GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE SEQUENCE TO C##DBELOPER;

ALTER USER C##DBELOPER DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS; 
ALTER USER C##DBELOPER QUOTA 1024M ON SYSTEM; 
